package coder

import (
	"fmt"
)

type AnthropicCoder struct {
	Model  string
	APIKey string
}

func NewAnthropicCoder(model, apiKey string) *AnthropicCoder {
	return &AnthropicCoder{Model: model, APIKey: apiKey}
}

func (a *AnthropicCoder) GenerateCode(plan string, fileContent string) (string, error) {
	fmt.Printf("[Coder] Anthropic (%s) is generating code (High Complexity mode)...\n", a.Model)
	// Integration with Anthropic API would go here.
	return "// Generated by Claude\nfunc TestAuth() {}", nil
}