package coder

import (
	"fmt"
)

type LocalLLMCoder struct {
	Endpoint string
	Model    string
}

func NewLocalLLMCoder(endpoint, model string) *LocalLLMCoder {
	return &LocalLLMCoder{Endpoint: endpoint, Model: model}
}

func (l *LocalLLMCoder) GenerateCode(plan string, fileContent string) (string, error) {
	fmt.Printf("[Coder] Local LLM (%s at %s) is generating code (Low Cost mode)...\n", l.Model, l.Endpoint)
	// Integration with OpenAI-compatible endpoint would go here.
	return "// Generated by Local LLM\nfunc TestAuth() {}", nil
}